{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-easy.utils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/easy.utils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/easy.utils/easy.utils_{{ version }}.tar.gz
  sha256: 86e3ece6f692868113ca444c3261c73c6d1be5db7dfea6634bf32ca9ce85e606

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-fastmatch
    - r-rlang
    - r-scales
  run:
    - r-base
    - r-dplyr
    - r-fastmatch
    - r-rlang
    - r-scales

test:
  commands:
    - $R -e "library('easy.utils')"           # [not win]
    - "\"%R%\" -e \"library('easy.utils')\""  # [win]

about:
  home: https://github.com/ycli1995/easy.utils
  license: MIT
  summary: Some utility functions for validation and data manipulation. These functions can be
    helpful to reduce internal codes everywhere in package development.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - theAeon
    - conda-forge/r

# Package: easy.utils
# Type: Package
# Title: Frequently Used Functions for Easy R Programming
# Version: 0.1.0
# Authors@R: person(given = "Yuchen", family = "Li", email = "ycli1995@outlook.com", role = c("aut", "cre"))
# Description: Some utility functions for validation and data manipulation. These functions can be helpful to reduce internal codes everywhere in package development.
# Depends: R (>= 4.1.0), methods
# Imports: dplyr, fastmatch, rlang, scales
# License: MIT + file LICENSE
# Encoding: UTF-8
# URL: https://github.com/ycli1995/easy.utils
# BugReports: https://github.com/ycli1995/easy.utils/issues
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Packaged: 2025-02-19 09:15:08 UTC; mydocker
# Author: Yuchen Li [aut, cre]
# Maintainer: Yuchen Li <ycli1995@outlook.com>
# Repository: CRAN
# Date/Publication: 2025-02-19 10:00:02 UTC
